### ISSUE TITLE
href in A element 

### ISSUE THREAD

**Issue by elri** [linkdata/jaws#7]
Adding href under "attributes" feels a bit weird given that the <a> tag's whole deal is the link, it could be its own thing? 

Using a dynamically rendered url as the href - something like `<a href="/salad/{{.Fruit.Bananas}}">` - doesn't seem feasible whichever way I try to do it, so maybe a warning for that should be added

**Comment by linkdata** [comment]
Try using the "print" template function:

```go
(print "href=\"/salad/" .Fruit.Bananas "\"")
```
